version: '3.8'

services:
  # SQL Server Database
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: job-tracker-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "11433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - job-tracker-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: job-tracker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - job-tracker-network

  # Backend API
  api:
    image: job-tracker-api:test
    container_name: job-tracker-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=JobTracker;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - ConnectionStrings__IdentityConnection=Server=mssql;Database=JobTrackerIdentity;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - Redis__ConnectionString=redis:6379
    depends_on:
      mssql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - job-tracker-network
    restart: unless-stopped

  # Frontend
  frontend:
    image: job-tracker-frontend:test
    container_name: job-tracker-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - api
    networks:
      - job-tracker-network
    restart: unless-stopped

volumes:
  mssql_data:
    driver: local
  redis_data:
    driver: local

networks:
  job-tracker-network:
    driver: bridge
